# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=65535)),
                ('name', models.CharField(max_length=65535)),
                ('docUrl', models.URLField()),
            ],
        ),
    ]
