# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_stat', '0002_remove_apientry_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updateTime', models.DateTimeField(editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='apientry',
            name='createTime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='apientry',
            name='updateTime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_stat.ApiEntry'),
        ),
    ]
