# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_stat', '0004_auto_20170605_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='apientry',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='historicalapientry',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
