# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_stat', '0007_auto_20170603_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestround',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testround',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
