# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_stat', '0008_auto_20170609_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestcase',
            name='commitTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='commitTime',
            field=models.DateTimeField(null=True),
        ),
    ]
