# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_stat', '0003_auto_20170605_0437'),
    ]

    operations = [
    ]
