# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpage',
            name='pageClass',
            field=models.TextField(max_length=65535, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='pageClass',
            field=models.TextField(max_length=65535, null=True),
        ),
    ]
