# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20170605_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('args', models.TextField()),
            ],
        ),
    ]
